[workspace]
members = [
    "crates/dendrited",
    "crates/dendrite-cli",
    "crates/dendrite-memory",
    "crates/dendrite-action",
    "crates/dendrite-guard",
    "crates/dendrite-updater",
    "crates/dendrite-protocol",
    "crates/dendrite-ebpf-common",
    "crates/dendrite-ui-server",
    "crates/dendrite-magi",
]
exclude = ["ebpf/dendrite-ebpf"]
resolver = "2"
