#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT/ebpf/dendrite-ebpf/Cargo.toml"
VMLINUX="$ROOT/ebpf/dendrite-ebpf/src/vmlinux.rs"

usage() {
  cat <<USAGE
Usage: $0 [--regenerate-vmlinux]

Builds the eBPF object (ebpf/dendrite-ebpf). vmlinux.rs (the aya-tool
generated kernel struct bindings task_struct/mm_struct/file rely on) is
normally already committed to the repo and reused as-is — this script only
(re)generates it when it's missing, or when asked to explicitly.

Flags:
  --regenerate-vmlinux  Regenerate vmlinux.rs against THIS machine's running
                        kernel even if a copy already exists (needed after a
                        kernel upgrade — see the warning this script prints
                        when the committed copy's kernel doesn't match
                        \`uname -r\`).
  -h, --help            Show this help.
USAGE
}

REGENERATE_VMLINUX=0
for arg in "$@"; do
  case "$arg" in
    --regenerate-vmlinux) REGENERATE_VMLINUX=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $arg" >&2; usage >&2; exit 2 ;;
  esac
done

export PATH="$HOME/.cargo/bin:$PATH"

APT_UPDATED=0
ensure_apt_packages() {
  if ! command -v apt-get >/dev/null 2>&1; then
    echo "Warning: apt-get not available — can't install: $*" >&2
    echo "  Install these yourself with your system's package manager, then re-run this script." >&2
    return 1
  fi
  if [[ "$APT_UPDATED" == 0 ]]; then
    sudo apt-get update
    APT_UPDATED=1
  fi
  sudo apt-get install -y "$@"
}

# --- vmlinux.rs: generate only when missing or asked to, never on every run ---
#
# This is a real kernel-struct-layout dependency, not a portable artifact:
# task_struct/mm_struct/file field offsets are specific to the exact kernel
# they were generated against (see the file's own header comment). The
# common case — the committed copy already matches (or is close enough to)
# this machine's kernel — costs nothing extra here; only a missing file or
# an explicit --regenerate-vmlinux triggers the toolchain checks below.
existing_kernel_release() {
  grep -oP 'dendrite:vmlinux-kernel-release:\s*\K\S+' "$VMLINUX" 2>/dev/null || true
}

if [[ -f "$VMLINUX" && "$REGENERATE_VMLINUX" != 1 ]]; then
  recorded="$(existing_kernel_release)"
  running="$(uname -r)"
  if [[ -n "$recorded" && "$recorded" != "$running" ]]; then
    echo "Warning: ebpf/dendrite-ebpf/src/vmlinux.rs was generated against kernel $recorded," >&2
    echo "  this machine is running $running. Struct layouts often stay compatible across a" >&2
    echo "  patch release, but if capture_process_identity()/capture_executable_identity() in" >&2
    echo "  main.rs start reading garbage (or the verifier starts rejecting the program), this" >&2
    echo "  mismatch is the first thing to check. Regenerate with:" >&2
    echo "    $0 --regenerate-vmlinux" >&2
  fi
else
  if [[ "$REGENERATE_VMLINUX" == 1 ]]; then
    echo "-- Regenerating vmlinux.rs (--regenerate-vmlinux) --"
  else
    echo "-- vmlinux.rs missing — generating it against this machine's kernel --"
  fi

  BTF_PATH="/sys/kernel/btf/vmlinux"
  if [[ ! -r "$BTF_PATH" ]]; then
    echo "Error: $BTF_PATH not present or not readable." >&2
    echo "  This kernel wasn't built with CONFIG_DEBUG_INFO_BTF, so there's no BTF to generate" >&2
    echo "  correct struct bindings from — vmlinux.rs cannot be produced on this machine." >&2
    exit 1
  fi

  if ! command -v bpftool >/dev/null 2>&1; then
    echo "bpftool not found — installing it..."
    ensure_apt_packages linux-tools-common "linux-tools-$(uname -r)" \
      || ensure_apt_packages bpftool \
      || { echo "Error: could not install bpftool automatically — install it yourself, then re-run." >&2; exit 1; }
  fi

  if ! command -v bindgen >/dev/null 2>&1; then
    echo "bindgen (bindgen-cli) not found — installing it..."
    cargo install bindgen-cli
  fi

  if ! command -v aya-tool >/dev/null 2>&1; then
    echo "aya-tool not found — installing it (lives inside the aya-rs/aya monorepo, not its own repo)..."
    cargo install --git https://github.com/aya-rs/aya -- aya-tool
  fi

  GENERATED="$(mktemp)"
  trap 'rm -f "$GENERATED"' EXIT
  aya-tool generate task_struct mm_struct file > "$GENERATED"

  {
    echo "//! Generated by \`aya-tool generate task_struct mm_struct file\` against this"
    echo "//! kernel's own BTF (\`/sys/kernel/btf/vmlinux\`) at generation time. Struct"
    echo "//! field offsets here are correct for the exact kernel this was generated"
    echo "//! on; they are NOT guaranteed portable to a different kernel"
    echo "//! version/build without regenerating. Do not hand-edit — regenerate"
    echo "//! instead if a field is missing or a kernel upgrade changes this"
    echo "//! program's target: \`scripts/build-ebpf.sh --regenerate-vmlinux\` (or just"
    echo "//! delete this file — the script regenerates it automatically when it's"
    echo "//! missing)."
    echo "//!"
    echo "//! dendrite:vmlinux-kernel-release: $(uname -r)"
    echo "#![allow("
    echo "    dead_code,"
    echo "    non_camel_case_types,"
    echo "    non_snake_case,"
    echo "    non_upper_case_globals,"
    echo "    unsafe_op_in_unsafe_fn,"
    echo "    clippy::all"
    echo ")]"
    echo
    cat "$GENERATED"
  } > "$VMLINUX"

  rm -f "$GENERATED"
  trap - EXIT
  echo "Wrote $VMLINUX (kernel $(uname -r))"
fi

# --- the actual build ---

# bpf-linker links against libelf/zlib at build and/or link time; not
# detectable via a simple `command -v` check the way a binary is, so these
# are just always ensured present before it's needed rather than probed for.
ensure_apt_packages libelf-dev zlib1g-dev || true

if ! command -v bpf-linker >/dev/null 2>&1; then
  echo "bpf-linker not found — installing it..."
  if ! command -v cargo-binstall >/dev/null 2>&1; then
    echo "Installing cargo-binstall first (so bpf-linker comes from a prebuilt release, not a" >&2
    echo "  from-source build needing a matching local LLVM — see https://github.com/aya-rs/bpf-linker#installation)..." >&2
    curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    # shellcheck source=/dev/null
    source "$HOME/.cargo/env" 2>/dev/null || true
  fi
  if command -v cargo-binstall >/dev/null 2>&1; then
    cargo binstall --no-confirm bpf-linker
  else
    echo "Warning: cargo-binstall install itself failed — falling back to 'cargo install bpf-linker'," >&2
    echo "  which needs a matching local LLVM/llvm-config and may fail the same way this just did." >&2
    cargo install bpf-linker
  fi
fi

if ! cargo +nightly --version >/dev/null 2>&1; then
  echo "Installing nightly toolchain (needed for eBPF)..."
  rustup toolchain install nightly
fi
if ! rustup component list --toolchain nightly --installed 2>/dev/null | grep -q '^rust-src'; then
  # bpfel-unknown-none is Tier 3 with no prebuilt std/core component —
  # -Z build-std=core compiles core from source for it instead, which
  # needs rust-src, not a prebuilt target (`rustup target add` for it
  # always fails: "no prebuilt artifacts available", which isn't a real
  # error, it's just the wrong fix).
  rustup component add rust-src --toolchain nightly
fi

cargo +nightly build \
  --manifest-path "$MANIFEST" \
  --target bpfel-unknown-none \
  -Z build-std=core \
  --release

echo "$ROOT/ebpf/dendrite-ebpf/target/bpfel-unknown-none/release/dendrite-ebpf"
